/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dQblw0e8F8R
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function card() {
  return (
    <Card className="flex items-center gap-4 p-4 sm:p-6">
      <Avatar className="h-16 w-16 sm:h-20 sm:w-20">
        <AvatarImage src="/placeholder-user.jpg" alt="@username" />
        <AvatarFallback>JP</AvatarFallback>
      </Avatar>
      <div className="grid gap-1">
        <div className="text-lg font-semibold">Jared Palmer</div>
        <div className="text-sm text-muted-foreground">jared@example.com</div>
      </div>
    </Card>
  )
}
